# This is a TOML document.
# hello
# my tesT
# Thisi s s test
# hello again

[program]

pgm= "pythong"
parms = "collect"
user = "jon2allen"
interval_seconds = 20 
status = "down"
# status can be up - meanint it starts running
# status down mesns - it should be running and is down.


[script]
location = "/home/jon2allen/scripts"
pgm = "alert.sh"
options = "logger"
throttle_minutes = 60
# throttle_minutes = how many minutes before script is
# executed after condition is met.


# end of file
